swagger: "2.0"
info:
  title: ChatBot Api
  description: API for MARK5826 chatbot.
  version: 1.0.0
host: 127.0.0.1:5000
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

definitions:
  Chatfuel_text:
    type: "object"
    properties:
      messages:
        type: "array"
        items:
          type: object
          properties:
            text:
              type: string


paths:
  /factor/highest:
    get:
      operationId: factor_highest
      tags:
        - Advertising Comparison 
      responses:
        200:
          description: "OK"
          schema:
              $ref : '#/definitions/Chatfuel_text'
        400:
          description: "Invalid status value"
  /factor/positive:
    get:
      operationId: factor_positive
      tags:
        - Advertising Comparison 
      responses:
        200:
          description: "OK"
          schema:
              $ref : '#/definitions/Chatfuel_text'
        400:
          description: "Invalid status value"
  /factor/negative:
    get:
      operationId: factor_negative
      tags:
        - Advertising Comparison 
      responses:
        200:
          description: "OK"
          schema:
              $ref : '#/definitions/Chatfuel_text'
        400:
          description: "Invalid status value"
  /suggestion:
    get:
      operationId: suggestion
      tags:
        - Advertising Comparison 
      responses:
        200:
          description: "OK"
          schema:
              $ref : '#/definitions/Chatfuel_text'
        400:
          description: "Invalid status value"